{% extends '../../framework/templates/default/default.html.swig' %}
{% block content %}

  {# include '../../project/line-demo/line-demo.html.swig' #}
  {# include '../../project/intro-inu/intro-inu.html.swig' #}
  {# include '../../project/skew-image/skew-image.html.swig' #}
  {# include '../../project/marquee-demo/marquee-demo.html.swig' #}
  {% include '../../project/fuzzy-text-demo/fuzzy-text-demo.html.swig' %}

{% endblock %}
